### ISSUE TITLE
ImportError on Running chatmof setup After Installation

### ISSUE THREAD

**Issue by Andy6M** [Yeonghun1675/ChatMOF#12]
Dear Yeonghun:
After successfully installing chatmof using pip, running the chatmof setup command results in an ImportError.

To Reproduce

Install chatmof with pip install chatmof.
Run chatmof setup.
See error:
`Traceback (most recent call last):
  File "/root/miniconda3/envs/chatmof/bin/chatmof", line 5, in <module>
    from chatmof.cli.main import main
    ...
  File "/root/miniconda3/envs/chatmof/lib/python3.9/site-packages/langchain/tools/python/__init__.py", line 13, in <module>
    raise_on_import()
  File "/root/miniconda3/envs/chatmof/lib/python3.9/site-packages/langchain/tools/python/__init__.py", line 3, in raise_on_import
    raise ImportError(
ImportError: This tool has been moved to langchain experiment. This tool has access to a python REPL. For best practices make sure to sandbox this tool. Read https://github.com/langchain-ai/langchain/blob/master/SECURITY.md To keep using this code as is, install langchain experimental and update relevant imports replacing 'langchain' with 'langchain_experimental'
`

My python version is 3.9.

Thanks!

**Comment by Yeonghun1675** [comment]
Hi @Andy6M,

Thank you for your interest in our research. We've checked and found that the location of the `python REPL` tool changed when langchain was updated. If you install langchain to version 0.0.235, you should be able to use it.

```bash
$ pip install langchain==0.0.235
```

We'll update the requirement as well.
