### ISSUE TITLE
Structure Generation Error

### ISSUE THREAD

**Issue by gokhanonderaksu** [Yeonghun1675/ChatMOF#17]
Hello! First of all, I would like to thank for bringing such a nice tool in the MOF literature. I assume I have done the exact steps with installation, but I have some problems with the generation part. Prediction or data search parts are working just fine. The error seems something like that: 

########## Question ##############################
Please enter the question below >>
Can you generate the structures with the largest surface area?

> Entering new ChatMOF chain...

> Entering new AgentExecutor chain...
The question is asking to generate a structure with the largest surface area.
Action: generator
Action Input: "Generate the structure with the largest surface area"

> Entering new Generator chain...

[Generator] Thought: I need to generate a material with the largest surface area.
[Generator] Objective: max
[Generator] Predict Properties: accessible_surface_area
load model : /home/lenovo/.local/lib/python3.10/site-packages/chatmof/database/load_model/accessible_surface_area/best.ckpt
Predicting DataLoader 0: 100%|████████████████████████████████████████████████████████| 178/178 [00:41<00:00,  4.26it/s]
load model : /home/lenovo/.local/lib/python3.10/site-packages/chatmof/database/load_model/accessible_surface_area/best.ckpt
Predicting DataLoader 0:   1%|▎                                                         | 1/163 [00:00<00:51,  3.16it/s]Error: Caught FileNotFoundError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lenovo/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lenovo/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lenovo/.local/lib/python3.10/site-packages/moftransformer/datamodules/dataset.py", line 199, in __getitem__
    ret.update(self.get_grid_data(cif_id, draw_false_grid=self.draw_false_grid))
  File "/home/lenovo/.local/lib/python3.10/site-packages/moftransformer/datamodules/dataset.py", line 123, in get_grid_data
    cell, volume, grid_data = self.get_raw_grid_data(cif_id)
  File "/home/lenovo/.local/lib/python3.10/site-packages/moftransformer/datamodules/dataset.py", line 107, in get_raw_grid_data
    with open(file_grid, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/chatmof/database/structures/hMOF/dia+N562+E205.grid'
. Continuing without this file.

Thanks for using CHATMOF!
Predicting DataLoader 0:   1%|▎                                                         | 1/163 [00:00<02:24,  1.12it/s]

It somehow searches for hMOF folder under database, but there is no folder either in the depository or loading scheme. How could I solve this issue?

Thanks in advance for your response.

Kind regards,

**Comment by Yeonghun1675** [comment]
Hi @gokhanonderaksu,

Thank you for being so interested in my chatmof. We have checked the issue and found it to be an issue with the hMOF zip file during setup. I have uploaded a new hMOF.zip and changed the setup to receive the corrected hMOF. Please let me know if you run into any further issues.

**Comment by gokhanonderaksu** [comment]
Hello, thanks for your response!

I have uninstalled and installed everything using "chatmof setup", as it downloaded corecof, hmof, and load_model folders. 
![chatmof folders](https://github.com/Yeonghun1675/ChatMOF/assets/107998101/463654da-52ae-48ae-aa8b-2593c485cef3)
But unfortunately I have still the same issue.

**Comment by Yeonghun1675** [comment]
The hMOF download link changed during the process of uploading a new database. Please update ChatMOF to version 0.2.2 and proceed with the setup again. If not, you can get it from the following link: https://figshare.com/articles/dataset/Database_for_ChatMOF/24287731

**Comment by gokhanonderaksu** [comment]
Hello again,

Yes, this time, generator works; however, there are some missing linker files that give such errors:
[Generator] Generate Structures: >>> [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/topologies/pcu.pickle'
Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.10/site-packages/pormake/database.py", line 81, in get_topology
    with pickle_path.open("rb") as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/topologies/pcu.pickle'
pcu:   0%|                                                               | 0/99 [00:00<?, ?it/s]WARNING:jax._src.xla_bridge:An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
pcu: 100%|██████████████████████████████████████████████████████| 99/99 [00:51<00:00,  1.91it/s]
>>> [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/topologies/dia.pickle'
Traceback (most recent call last):
  File "/home/lenovo/.local/lib/python3.10/site-packages/pormake/database.py", line 81, in get_topology
    with pickle_path.open("rb") as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/topologies/dia.pickle'
dia:   9%|█████▏                                                 | 9/96 [00:07<01:03,  1.37it/s]>>> BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E310.xyz'.
ERROR:generate_mof.log:BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E310.xyz'.
>>> BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E649.xyz'.
ERROR:generate_mof.log:BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E649.xyz'.
>>> BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E515.xyz'.
ERROR:generate_mof.log:BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E515.xyz'.
>>> BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E267.xyz'.
ERROR:generate_mof.log:BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E267.xyz'.
>>> BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E515.xyz'.
ERROR:generate_mof.log:BuildingBlock loading is failed: [Errno 2] No such file or directory: '/home/lenovo/.local/lib/python3.10/site-packages/pormake/database/bbs/E515.xyz'.

I checked folders both for topologies and linkers. For topologies, probably there is a print error regarding "pormake". For linkers, yes, they are missing. Could you also provide an update for the linker files, or how to download them and integrate them to corresponding folders?

Thank you so much once again!

**Comment by Yeonghun1675** [comment]
Hi @gokhanonderaksu,

1. For topology, you need to create a pickle file. The pickle file used to be generated automatically, but it seems to need to be generated occasionally after a pormake update. Try running pormake serialize from that github. (https://github.com/Yeonghun1675/bulk_pormake_generation)

2. For the linker, there are 234 edges and 719 nodes. For nodes and edges beyond this, the genetic algorithm has created the wrong child. This didn't happen when I generated it. Take a look at the logs to see the children and parents generated by genetic, and let me know if you see anything strange.
